### ISSUE TITLE
please increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [dttzyjw0012/PhantomProcessesSavior#2]
Can you please increase `versionCode` with each release – as that's what Android uses to keep versions apart and decide whether an APK is considered an update? Your second release still has that on `1`:

    package: name='com.yhc.phantom.processes.savior' versionCode='1' versionName='2.0'

I further wonder: the readme says it requires Xposed and Magisk – but there#s no Magisk module here. Guess that's meant as Magisk hosting the Xposed framework (e.g. LSPosed)? Is there some more description on the Xposed module (and maybe an icon to present it with)? I was thinking to include it with [my repo](https://apt.izzysoft.de/fdroid) if that's OK with you then.

**Comment by dttzyjw0012** [comment]
Oh, I forgot to changed the versionCode because I am using the XP module CorePatch which can ignore the version of the old app  install app. Now, it had been updated both code and apk file released. Thank you for your reminding.

The readme says "Magisk" meant as Magisk hosting the Xposed framework (e.g. LSPosed)? indeed. The KernelSU and other Xposed framework maybe also work, but I will not test on these frameworks because they are not in common use. The description and icon will be not added. Its function is same to run the adb command, 

'adb shell "settings put global settings_enable_monitor_phantom_procs false" '

on the higher version of Android. I do not have much more time to develop for design or usability, if you want to uninstall it, you can do in LSPosed.

You can use it everywhere if obey the opensource license.

**Comment by IzzySoft** [comment]
Thanks a lot! Added it here then. It should [show up](https://apt.izzysoft.de/packages/com.yhc.phantom.processes.savior/) with the next sync around 7 pm UTC.

Thanks also for the details on what it does! I've included that with the description, so the listing will look like this:

![image](https://github.com/dttzyjw0012/PhantomProcessesSavior/assets/6781438/1eac772e-d6c4-492c-a218-09e5bfa48c35)

And yes, your license will of course be obeyed by me. That's at the core of my repo (it's all about F/LOSS apps, so the corresponding licenses are an important part).

PS: If you want to, you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app in my repo e.g. from your Readme.
